# WIDOCO Configuration File for Radnetz Ontology
# https://github.com/dgarijo/Widoco

ontologyTitle=Radnetz Ontologie (GDI-DE)
ontologyName=Radnetz Ontologie
ontologyPrefix=gdi
ontologyNamespaceURI=https://registry.gdi-de.org/up3/ontology/
ontologyRevisionNumber=2.0.0

authors=Dr. Claire Ponciano
authorsURI=
authorsInstitution=
authorsInstitutionURI=

dateOfRelease=2026-09-29
thisVersionURI=https://registry.gdi-de.org/up3/ontology/
latestVersionURI=https://registry.gdi-de.org/up3/ontology/

abstract=Diese Ontologie beschreibt die Anforderungen und das Datenmodell f\u00FCr das Radnetz Deutschland (GDI-DE UP-3) sowie administrative Einheiten (Destatis GV2Q) im Rahmen der Geodateninfrastruktur Deutschland (GDI-DE) und des Bundesamtes f\u00FCr Logistik und Mobilit\u00E4t (BALM), harmonisiert mit GeoSPARQL und INSPIRE Road Transport Network. / This ontology defines the German Cycling Network data model (GDI-DE UP-3) and administrative units (Destatis GV2Q) within the German Spatial Data Infrastructure (GDI-DE) and the Federal Office for Logistics and Mobility (BALM), aligned with GeoSPARQL and INSPIRE Road Transport Network.

licenseName=Creative Commons Attribution 4.0 International (CC BY 4.0)
licenseURI=https://creativecommons.org/licenses/by/4.0/
status=Specification
