# WIDOCO Configuration File for Radnetz Ontology
# https://github.com/dgarijo/Widoco

ontologyTitle=Radverkehr Ontologie (GDI-DE)
ontologyName=Radnetz Ontologie
ontologyPrefix=gdi
ontologyNamespaceURI=https://registry.gdi-de.org/up3/ontology/

authors=Dr. Claire Ponciano
authorsURI=
authorsInstitution=
authorsInstitutionURI=

dateOfRelease=2026-09-01
thisVersionURI=https://registry.gdi-de.org/up3/ontology/
latestVersionURI=https://registry.gdi-de.org/up3/ontology/

abstract=Diese Ontologie beschreibt die Anforderungen und das Datenmodell f\u00FCr das Radnetz im Rahmen der Geodateninfrastruktur Deutschland (GDI-DE) und des Bundesamtes f\u00FCr Logistik und Mobilit\u00E4t (BALM). Sie modelliert Streckenabschnitte, Netzknoten, Routen sowie zugeh\u00F6rige Codelisten und Eigenschaften f\u00FCr den Radverkehr. / This ontology defines the cycling network data model and requirements within the German Spatial Data Infrastructure (GDI-DE) and the Federal Office for Logistics and Mobility (BALM), specifying route segments, nodes, itineraries, and associated properties and codelists for bicycle traffic.

licenseName=Creative Commons Attribution 4.0 International (CC BY 4.0)
licenseURI=https://creativecommons.org/licenses/by/4.0/
status=Specification
